import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  avatarImageUrl,
  codeFromAvatarUrl,
  coverCharacterUrl,
  isGeneratedAvatar,
  isShareCode,
  studioUrl,
} from "./arkplay-avatar.ts";

/** A real code, generated by the engine and rendered successfully by the live
    service before this test was written. Truncated is not good enough: the
    shape check has a length floor and a short sample would pass for the wrong
    reason. */
const CODE =
  "A2qX9l_tDEEUSpV6WJ70gW2bIWfIaaqdgLCNTybLZowEh0XrIlKogLJ2iQx4Bqkz7ELaB9TU5OdRUa2yk62MSlW0n2tf4sNVhLGLN7LUDJlFl51VIRlKlMPrWNaRr68tupGUrVr6IPZzi-KWtWgFV1mYzfRx_ZTZDniVKJtn29rIhZlu8DKnLSLaxohCRiY6NdKF8FZLvOtmSBFVQLYBi42RFb25lvNFCrPqztzdNUsjxSTFqSrqHTwLWV";

describe("the picture for a code", () => {
  it("builds a render URL on the service", () => {
    const url = new URL(avatarImageUrl(CODE));
    assert.equal(url.pathname, `/avatar/v1/render/${CODE}.png`);
    assert.equal(url.searchParams.get("crop"), "portrait");
    assert.equal(url.searchParams.get("size"), "256");
  });

  it("offers the whole character for a cover", () => {
    const url = new URL(avatarImageUrl(CODE, { crop: "full", size: 512 }));
    assert.equal(url.searchParams.get("crop"), "full");
    assert.equal(url.searchParams.get("size"), "512");
  });

  /*
    A KEY IN AN <img src> IS A KEY IN EVERY PROXY LOG between here and the
    reader. Rendering needs no credential at all — verified against the live
    service — so there is never a reason for one to appear here.
  */
  it("never carries a credential", () => {
    const url = avatarImageUrl(CODE, { crop: "full" });
    assert.doesNotMatch(url, /apk_|api[_-]?key|token|secret|authorization/i);
  });

  /*
    THE SERVICE DRAWS ITS OWN SCENE UNLESS TOLD NOT TO. Verified against the
    live render: with the default the PNG's corners come back an opaque
    #272F42, so a character composited over a profile background would cover
    that background with a dark rectangle instead of standing on it.
  */
  it("leaves the scene alone unless a caller turns it off", () => {
    assert.equal(new URL(avatarImageUrl(CODE)).searchParams.get("background"), null);
    assert.equal(
      new URL(avatarImageUrl(CODE, { background: false })).searchParams.get("background"),
      "false",
    );
  });

  it("cuts the cover character out of its scene", () => {
    const url = new URL(coverCharacterUrl(CODE));
    assert.equal(url.searchParams.get("crop"), "full", "the whole figure, not a portrait");
    assert.equal(url.searchParams.get("background"), "false", "nothing may hide the ground");
  });

  /* The code must survive the round trip, or re-editing a cover breaks. */
  it("keeps the share code readable back out of a cover URL", () => {
    assert.equal(codeFromAvatarUrl(coverCharacterUrl(CODE)), CODE);
  });
});

/*
  A PERSON MUST BE ABLE TO REOPEN THE EDITOR ON THE AVATAR THEY HAVE.

  Square has nowhere of its own to keep the code yet, and does not need one:
  the render URL contains it by construction. Reading our own format back is
  the difference between an avatar you can edit and one you must rebuild from
  nothing every time.
*/
describe("recovering the code from a saved avatar", () => {
  it("reads it back out of a render URL", () => {
    assert.equal(codeFromAvatarUrl(avatarImageUrl(CODE)), CODE);
    assert.equal(codeFromAvatarUrl(avatarImageUrl(CODE, { crop: "full", format: "svg" })), CODE);
  });

  it("survives the query being changed or dropped", () => {
    const bare = `https://game-server.tsionark.com/avatar/v1/render/${CODE}.png`;
    assert.equal(codeFromAvatarUrl(bare), CODE);
    assert.equal(codeFromAvatarUrl(`${bare}?crop=full&size=512&v=2`), CODE);
  });

  /*
    An uploaded photograph is a real profile picture that simply is not a
    generated avatar. Answering a code for it would reopen the editor on
    something that was never made in it.
  */
  it("answers null for a photograph or a placeholder", () => {
    assert.equal(codeFromAvatarUrl("https://cdn.example/me.jpg"), null);
    assert.equal(codeFromAvatarUrl("/avatar/artwork-3.svg"), null);
    assert.equal(codeFromAvatarUrl(null), null);
    assert.equal(codeFromAvatarUrl(""), null);
    assert.equal(codeFromAvatarUrl("not a url at all"), null);
  });

  it("refuses a render path whose code is not one", () => {
    assert.equal(codeFromAvatarUrl("https://x.test/avatar/v1/render/short.png"), null);
    assert.equal(
      codeFromAvatarUrl("https://x.test/avatar/v1/render/has spaces and punctuation!.png"),
      null,
    );
  });

  it("tells a generated avatar from an uploaded one", () => {
    assert.equal(isGeneratedAvatar(avatarImageUrl(CODE)), true);
    assert.equal(isGeneratedAvatar("https://cdn.example/me.jpg"), false);
  });
});

describe("the share code shape", () => {
  it("accepts a real one", () => {
    assert.ok(isShareCode(CODE));
  });

  it("rejects what a broken image would be made of", () => {
    for (const bad of ["", "short", "has space", "a/b", "a.b", null, undefined]) {
      assert.ok(!isShareCode(bad as string), String(bad));
    }
  });
});

describe("opening the editor", () => {
  it("tells the studio who it may answer", () => {
    // The studio checks this before it postMessages back, so it must be the
    // caller's real origin rather than a guess.
    const url = new URL(studioUrl("https://square.tsionark.com"));
    assert.equal(url.searchParams.get("embed"), "1");
    assert.equal(url.searchParams.get("origin"), "https://square.tsionark.com");
    assert.equal(url.pathname, "/avatar/studio/");
  });

  it("reopens on an existing avatar when there is one", () => {
    assert.equal(new URL(studioUrl("https://sq.test", CODE)).searchParams.get("code"), CODE);
    assert.equal(new URL(studioUrl("https://sq.test", null)).searchParams.get("code"), null);
  });
});
